### ISSUE TITLE
Can the condition that DM::depends_on() checks really happen?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#103]

**Comment by mulkieran** [comment]
@agrover why does this method exist?

**Comment by agrover** [comment]
It was used in Melvin to make sure you couldn't add an LVM LV as a PV in its own VG, equivalent of LVM2's dev_manager_device_uses_vg function.

See https://github.com/agrover/melvin/blob/b4c9075fc98595c68778d6206b3e59e79476835b/src/vg.rs#L126

**Comment by mulkieran** [comment]
Related: #106. Here the Device is not a DM device, but could be an arbitrary one.

**Comment by mulkieran** [comment]
Resolved by removing the method in #137.
