### ISSUE TITLE
ThinPoolDev::setup fails for an existing device

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#120]
If we are reloading against existing DM devices, the call to `thin_check` in `ThinPoolDev::setup` will fail, since the metadata device is in use.

It probably makes sense to move the "device exists" handling code from `::new` to `::setup` and make it work better with the thin_check, so we only call thin_check if the DM devices are actually being created.

**Comment by mulkieran** [comment]
We need to find out why our test in stratisd is succeeding.

Related: https://github.com/stratis-storage/stratisd/pull/502.

**Comment by agrover** [comment]
@trgill 's analysis was that the old version of `thin_check` used in the CI environment is to blame for the test succeeding when it shouldn't.

**Comment by mulkieran** [comment]
We believe that newer versions of ```thin_check``` return an error if the the meta device is "in use" by the thinpool device. What does "in use" mean, though?

**Comment by mulkieran** [comment]
Calling ```thin_check``` conditionally was implemented in #154 .
