### ISSUE TITLE
Is the size of the ThinPoolDev always the size of its data dev?

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#133]
If it is, then it doesn't make any sense to pass both the size and the data dev as arguments to new() and since we must pass the data dev we should drop the size.

**Comment by mulkieran** [comment]
@agrover @trgill Could you give this your consideration?

**Comment by agrover** [comment]
I believe it is, yes.

**Comment by trgill** [comment]
right

**Comment by mulkieran** [comment]
Ok, thanks. I'll remove the param.
