### ISSUE TITLE
Handling dev_t, and major and minor parts

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#147]
Currently, `Device` has a u32 for major ID and u8 for minor ID. We want to use a u32 for minor as well, since Linux and device-mapper support minor numbers greater than 2^8.

Also, the u64 that Device::from() takes is ambiguous. See /usr/include/bits/sysmacros.h. Currently it's doing a zero-extended version of the legacy 16 bit dev_t representation, but passing a glibc `dev_t` will not be correct. e.g. passing the return value from metadata.st_rdev() into Device::from() is wrong. So that's the issue with userspace dev_t.

The devno embedded in DM ioctls we also have an issue. They are encoded differently (as described accurately in that sysmacros.h file) so constructing a Device from that field will also need to be done properly.

**Comment by agrover** [comment]
We will need this PR merged: https://github.com/rust-lang/libc/pull/750

**Comment by mulkieran** [comment]
How come our tests are passing?

**Comment by agrover** [comment]
The alternate formats keep the low 16 bits (8bit maj 8bit min) the same for backwards compatibility. I'm assuming we're never using major or minor values above 256.
