### ISSUE TITLE
ThinDev:: *_fs methods are not internal errors

### ISSUE THREAD

**Issue by trgill** [stratis-storage/devicemapper-rs#15]
failures on ThinDev:: *_fs methods are not internal errors.  However, it's not clear  what better options current error hierarchy has to offer. 

The basic problem is that the error string might be a helpful thing to include in the error, but nix, which would be the natural choice, prefers just to return the error code.

**Comment by mulkieran** [comment]
These methods are no longer in device mapper, and in stratisd they do not return InternalError.
