### ISSUE TITLE
Need to reconsider how we teardown devices

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#158]
We always specify them by name.

We now know that this can lead to troublesome bugs, at least with ThinDevs.

The problem is that it is possible to constructs two ThinDev's with the same name in a pool. When you call ```device_remove()``` passing the name, it is not clear what happens, but it's not always going to be the right thing. Options are:

1. Add a third constructor to DevId, and specify the device's by their device number.
2. Start attaching devicemapper uuids to the devices and specify the device's by these uuids.

**Comment by mulkieran** [comment]
This also makes the current implementation of ```device_exists``` questionable.

**Comment by agrover** [comment]
> The problem is that it is possible to constructs two ThinDev's with the same name in a pool.

how is this possible??

**Comment by mulkieran** [comment]
My tests are also proving that it is impossible to create two device mapper devices with the same name: #161. This must have been a strange behavior w/ setup that I misinterpreted.

**Comment by mulkieran** [comment]
This was a false alarm, and it just indicates that more careful testing is needed in #159.
