### ISSUE TITLE
At some time it might make sense to put some parts of devicemapper into a core module

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#166]
Or to pull out non-core parts into a separate library.

**Comment by mulkieran** [comment]
This time is getting ever closer.

**Comment by mulkieran** [comment]
Closer still. It is probably easier to do this, then put in error_chain then to put in error_chain and then do this.

**Comment by mulkieran** [comment]
@agrover ?

**Comment by agrover** [comment]
I see there being delineated high and low-level APIs in dm-rs, but what would be the benefit of putting them in separate crates?

**Comment by mulkieran** [comment]
Ease of maintenance, greater rigor, more relaxed requirements for hoped for user contributions to outer layer, say for a new type of dm device.

**Comment by agrover** [comment]
Ease of maintenance seems to favor a single crate. We already see linked updates to dm and stratisd taking extra time, wouldn't this just make it worse?

**Comment by mulkieran** [comment]
I'm not sure they take so much extra time (above the actual development time, which would have to happen anyway). I've been working to get things together so we have stratisd updates all queued up by the time we do the devicemapper release. Releases to crates.io are as easy as to PyPi. And, due to cargo, it just as easy to do the CI against a branch as to do it against a release. So long as we use these facilities properly, the cost should be vanishingly small.

**Comment by mulkieran** [comment]
Note that everything in types.rs would belong in the core.

**Comment by mulkieran** [comment]
We still return ```fmt::Result``` from a bunch of display methods in core as well as ```core::Result``` from serialize and deserialize methods.

**Comment by mulkieran** [comment]
error-chaining of core devicemapper is completed. See #206 .

**Comment by mulkieran** [comment]
We need a name! I think the core should keep devicemapper-rs. So the outer layer should be called "dm-devices", perhaps.

**Comment by mulkieran** [comment]
I'll close this in favor of #220. But this one has the better notes.

**Comment by mulkieran** [comment]
Whoops! I failed to properly close it.
