### ISSUE TITLE
understand implications of making a snapshot larger / smaller than the origin

### ISSUE THREAD

**Issue by trgill** [stratis-storage/devicemapper-rs#177]
The DM documentation is not clear on the topic.

**Comment by agrover** [comment]
Well a snapshot, after being created, is just a thin-provisioned volume. So, what are the implications of making a thin volume larger or smaller? Can you clarify what this issue is asking?

**Comment by mulkieran** [comment]
Note: We don't know whether ```ThinDev::snapshot()``` should take a size parameter, perhaps optional or perhaps not.

**Comment by trgill** [comment]
I think this issue can be closed.
