### ISSUE TITLE
Figure out why clippy thinks AsciiExt is unused in types.rs

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#200]
If possible, find out how we can remove the annotation.

This may just be some kind of version difference between stable and nightly.

**Comment by agrover** [comment]
https://users.rust-lang.org/t/psa-dealing-with-warning-unused-import-std-ascii-asciiext-in-today-s-nightly/13726

**Comment by mulkieran** [comment]
Sounds good. We'll remove it when we start getting different errors.
