### ISSUE TITLE
bad block relocation target

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#201]
Could this be useful at some point?

https://www.redhat.com/archives/dm-devel/2007-February/msg00049.html

**Comment by mailinglists35** [comment]
original evms patch says "Copyright IBM"
now that ibm owns redhat, could that patch get resurrected for recent kernels?

**Comment by mulkieran** [comment]
> original evms patch says "Copyright IBM"
> now that ibm owns redhat, could that patch get resurrected for recent kernels?

This is just a Rust wrapper for devicemapper, not devicemapper itself. I think that the proper place to bring that issue up is on dm-devel, which is the official devicemapper mailing list.

**Comment by mulkieran** [comment]
Closing as just too speculative. If this target does resurface, we will know about it, and if desirable, include it in our planning.
