### ISSUE TITLE
Let's do a new devicemapper version

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#218]
It has lost its dependency on ```custom_derive``` crate and there has been one minor API change. It would be a convenience for everybody if we got this in, I think. Until we do, stratisd will continue to depend on ```custom_derive```.

**Comment by mulkieran** [comment]
@agrover ?

**Comment by agrover** [comment]
👍 !

**Comment by mulkieran** [comment]
Ok. Here goes.

**Comment by mulkieran** [comment]
Done!
