### ISSUE TITLE
Break into high-level and low-level layers

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#220]
@mulkieran I just wanted to open this since you're working on it (#216, #217) but there was not an issue (unless I missed it.) Do you want to talk about why you think this is a good idea? Are you aiming for separate crates, or separate git repos? (These need not be tied, see "cargo workspaces".) and why is this better than the status quo?

**Comment by mulkieran** [comment]
Also #27.

**Comment by mulkieran** [comment]
Broke the core stuff out into a sub-module a while ago, and it doesn't make sense to have further plans to break out into separate libraries at this time, so might as well close.
