### ISSUE TITLE
thinpooldev::status() should deal with pool mode PM_FAIL

### ISSUE THREAD

**Issue by trgill** [stratis-storage/devicemapper-rs#235]
status typically returns the results from:

                DMEMIT("%llu %llu/%llu %llu/%llu ",
                       (unsigned long long)transaction_id,
                       (unsigned long long)(nr_blocks_metadata - nr_free_blocks_metadata),
                       (unsigned long long)nr_blocks_metadata,
                       (unsigned long long)(nr_blocks_data - nr_free_blocks_data),
                       (unsigned long long)nr_blocks_data);

but if the pool mode is PM_FAIL - it only returns:

                if (get_pool_mode(pool) == PM_FAIL) {
                        DMEMIT("Fail");
                        break;
                }

The documentation indicates:

```
	In serious cases where even a read-only mode is deemed unsafe
	no further I/O will be permitted and the status will just
	contain the string 'Fail'.  The userspace recovery tools
	should then be used.
```

currently we've got an assertion in thinpooldev::status():

```
        assert!(status_vals.len() >= 8,
                "Kernel must return at least 8 values from thin pool status");
```

**Comment by mulkieran** [comment]
yes, but we check for the presence of "Fail" before that assertion. Are you seeing a failure?

**Comment by mulkieran** [comment]
PS. If we know an easy way to make a devicemapper device enter its failed mode that would be great for adding to devicemapper tests.

**Comment by trgill** [comment]
Ugh - sorry for the noise.  

I'll open an issue to "write a test for DM_FAIL".
