### ISSUE TITLE
Eliminate use of unwrap()

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#26]
We have some low-level code that uses a lot of `unwrap`, since if the unwrap fails, then basically the kernel API changed and we rely on it to remain constant.

However, it would be nice to instead use `expect()`, which if such a case did happen, it would at least be a chance for us to provide a hint as to what constant the kernel just violated 😃

**Comment by mulkieran** [comment]
```DM::do_ioctl``` and ```DM::list_devices()``` are now the sole offenders.

**Comment by mulkieran** [comment]
But we have some improper ```expects()``` as well.
