### ISSUE TITLE
nix 0.10

### ISSUE THREAD

**Issue by ignatenkobrain** [stratis-storage/devicemapper-rs#263]
Would be nice if we could switch to nix 0.10

**Comment by ignatenkobrain** [comment]
Same for stratisd

**Comment by mulkieran** [comment]
This won't be as straightforward as I was hoping. nix 0.10 requires libc 0.2.36, but it appears that there is a least some other library that we use that transitively depends on libc that requires a lower version. We have to work out the puzzle.

```
[mulhern@localhost devicemapper-rs]$ cargo tree
devicemapper v0.16.0 (file:///home/mulhern/my-contributions/devicemapper-rs)
├── bitflags v1.0.1
├── error-chain v0.11.0
│   └── backtrace v0.3.4
│       ├── backtrace-sys v0.1.16
│       │   └── libc v0.2.34
│       ├── cfg-if v0.1.2
│       ├── libc v0.2.34 (*)
│       └── rustc-demangle v0.1.5
├── libc v0.2.34 (*)
├── macro-attr v0.2.0
├── newtype_derive v0.1.6
├── nix v0.9.0
│   ├── bitflags v0.9.1
│   ├── cfg-if v0.1.2 (*)
│   ├── libc v0.2.34 (*)
│   └── void v1.0.2
└── serde v1.0.24
```

**Comment by mulkieran** [comment]
Whoops. I think I may just have gotten out of the mess.

**Comment by agrover** [comment]
@ignatenkobrain I think this one is on its way to getting resolved but please next time if you give us a little bit more justification that'd be appreciated too 😃 Does this have something to do with your upstream nix work on making statvfs available on more archs?

**Comment by ignatenkobrain** [comment]
@agrover sure! No, that's because I don't want to keep multiple versions of crates in Fedora :P
