### ISSUE TITLE
"the clippy plugin is being deprecated, please use cargo clippy or rls with the clippy feature"

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#315]
I saw this warning on a recent clippy run. We have to figure out what it means and follow the advice.

**Comment by agrover** [comment]
Maybe this is good news?

**Comment by mati865** [comment]
https://github.com/rust-lang-nursery/rust-clippy/pull/2712
Using clippy as subcommand is long time preferred solution. Now it's just even more preferred.

What needs to be done is removing clippy from `Cargo.toml` and `src/lib.rs` and installing it via `cargo install clippy` instead. Then run it from Makefile like that: `cargo clippy`.

**Comment by mulkieran** [comment]
Well, I'm giving it a go: https://github.com/stratis-storage/devicemapper-rs/pull/322.
