### ISSUE TITLE
Re-export functions or structs?

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#32]
Now that things are a little better broken up by #28, I'd like to raise the question of which identifiers we should re-export at the top level. See [this](https://doc.rust-lang.org/book/crates-and-modules.html#re-exporting-with-pub-use).

I was thinking we make it nicer to use the HL API by re-exporting, but not re-export the LL stuff. @trgill what's your take?

**Comment by trgill** [comment]
Just to make sure I understand. :-) 

You are thinking we hide the contents/functions of dm.rs, device.rs and deviceinfo.rs?

For example, we'd remove the dm parameter from ThinDev::new() etc?

**Comment by agrover** [comment]
It's been a while since I had my head down in it, but I was just thinking we want to make it easy as we can to use the high level (HL) API, and still make the LL API available but tuck it down another level, perhaps. But, there are LL structs e.g. Device, DeviceInfo, DM that HL also needs, and these probably need to be at the toplevel too.

Do you think this goal of saving HL users from dealing with the LL details achievable? Or maybe it's just not realistic or that big a win, I don't know.

Specifically for `DM`.. passing it in makes the HL API more complicated but haven't yet seen a way, if it were not passed in, of avoiding pathological cases where `DM` structs get created/destroyed in huge, inefficient numbers.

**Comment by trgill** [comment]
Yes, I think the goal of saving HL users from dealing with the details is achievable.  I think we are fairly close.  I'll put a PR together.

**Comment by trgill** [comment]
@agrover the latest PRs address these issues, right?

**Comment by agrover** [comment]
Yes I think so! Closing. Thanks!
