### ISSUE TITLE
ThinDev::setup should set the dm_cookie in the same way as ThinDev::new

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#330]
It looks this way to me, anyway.

**Comment by tasleson** [comment]
@mulkieran Yes, and so should snapshot.  I'll tackle this and add unit tests for all three to ensure this is working as expected.

**Comment by tasleson** [comment]
Addressed with https://github.com/stratis-storage/devicemapper-rs/pull/334
