### ISSUE TITLE
devicemapper should dereference non-null pointers directly instead of using as_ref

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#434]
There are idioms like:

```
(result.as_ptr() as *const dmi::Struct_dm_name_list)
                        .as_ref()
                        .expect("pointer to own structure result can not be NULL")
```
and others that are much less clear about why the expect() should hold.

These can be simplified to:

```&*(result.as_ptr() as *const dmi::Struct_dm_name_list)```

because it is devicemapper that is managing that memory, and so the pointer is certainly not null.

**Comment by theyoyojo** [comment]
So, changes like this?
<pre>

diff --git a/src/core/dm.rs b/src/core/dm.rs
index 94e68b9..32972fc 100644
--- a/src/core/dm.rs
+++ b/src/core/dm.rs
@@ -218,9 +218,7 @@ impl DM {
 
             loop {
                 let device = unsafe {
-                    (result.as_ptr() as *const dmi::Struct_dm_name_list)
-                        .as_ref()
-                        .expect("pointer to own structure result can not be NULL")
+                    &*(result.as_ptr() as *const dmi::Struct_dm_name_list)
                 };
 
                 let slc = slice_to_null(&result[size_of::<dmi::Struct_dm_name_list>()..])

**Comment by mulkieran** [comment]
Yes. There are actually two parts to this problem.

1. The first part is the transformation, exactly like that.
2. The second part is actually verifying that it is true that the pointer can not be NULL. We always have an expect("<some string>") there, so the code is always asserting that the pointer can not be NULL. Sometimes we have the completely wrong reason, e.g., "assume all parsing succeeds", unfortunately.
But the second half of the problem is making sure that our assumption that the pointer can never be NULL is correct. And that involves finding out where that slice actually originated. Oh, and sometimes

* ```as_ptr()``` -> ```as_mut_ptr()```
* ```as_ref()``` -> ```as_mut()```

also.

**Comment by mulkieran** [comment]
@theyoyojo Better hold off on this. I'm not so sure about non-NULLness anymore.

**Comment by theyoyojo** [comment]
nice
