### ISSUE TITLE
Handling adjacent segments passed to LinearDev::extend()

### ISSUE THREAD

**Issue by agrover** [stratis-storage/devicemapper-rs#44]
see https://github.com/stratis-storage/devicemapper-rs/pull/43. That PR tries to coalesce adjacent segments between last existing entry and first new entry, but doesn't do anything to coalesce if adjacent segments are passed in.

**Comment by mulkieran** [comment]
Adding to this that it might be sensible to use a data structure for a collection of Segments. Add is probably a bad name for the combination of two bunches of segments, extend probably is better.

**Comment by agrover** [comment]
Based upon what I just said in #129, my opinion is we should not fixup adjacent segments beyond the last/first fixup in `extend`, and therefore I'm in favor of closing this issue.

**Comment by mulkieran** [comment]
Closed by #134 (in which the behavior of ```extend()``` is specified in header comment).
