### ISSUE TITLE
Robustify our tests so they don't assume only the devices they created exist

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#465]
The problem is that if there are other devicemapper devices, not created by the tests, hanging around, these tests will fail. Presumably they were always run previously in a context where there were no other devicemapper devices about.

In some cases, all this would need would be to adapt the condition tested to not require that assumption, but there might be some more difficult ones.

Two examples which go wrong are:
* core::dm::tests::sudo_test_list_devices
* core::dm::tests::sudo_test_list_devices_empty

**Comment by mulkieran** [comment]
Need to talk about how to test this first.

**Comment by waltdisgrace** [comment]
I can think of several ways to approach this:

1. Before performing any tests, find out which, if any, devices already exist. Store identifiers for these devices in a data structure or file. Perform all tests in such a way that all of the devices corresponding to the stored identifiers are **not** taken into account.
2. Before performing any tests, find out which, if any, devices already exist. Store all necessary information for re-creating these devices in a data structure or file. Remove all of the devices. Perform all of the tests. Re-create the devices that you removed.
3. Whenever you perform a test that creates a device, store an identifier for said device in a data structure or file. Perform all tests that don't create devices in such a way that **only** the devices corresponding to the stored identifiers are taken into account.
4. Rely on a standardized test device nomenclature for distinguishing which devices are relevant for testing.

**Comment by waltdisgrace** [comment]
Closed by: #521.
