### ISSUE TITLE
Travis devicemapper-rs tests failing regularly with EBUSY

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/devicemapper-rs#557]
@mulkieran Travis tests were failing for @waltdisgrace pretty regularly with EBUSY on different loopback device tests every time. We seem to have gotten #556 to pass by rerunning it enough times but we should potentially look into what's going on here. I don't think this has anything to do with the code changes, so we may have to think about how we're testing in devicemapper-rs.

**Comment by mulkieran** [comment]
Yep, I think this was always a bit of a problem, and I think it's just been happening more and more often. We will have to find a better way, maybe the delay and wait for a particular thing to be true technique will work here, too.

**Comment by mulkieran** [comment]
We need to start taking this seriously, it is such a pain.

**Comment by mulkieran** [comment]
Pushing to September in hopes that #568 will keep the problem from being annoying for a while.

**Comment by mulkieran** [comment]
yeah, that sure worked. Let's not bother to think about it unless it starts bothering us again.
