### ISSUE TITLE
Remove Build Status link from README

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#587]
It could be misleading, as it may indicate an uninteresting build failure. If we drop Travis it will be quite useless. I don't mind the crate.io badge as much, it's not going to be so volatile.

**Comment by jbaublitz** [comment]
I would hold off on this unless you generally think this information is not useful. Github actions may have a similar API to display that information.

**Comment by mulkieran** [comment]
> I would hold off on this unless you generally think this information is not useful. Github actions may have a similar API to display that information.

I'm sure GitHub actions supplies something similar. But it's not that sort of transient, from CI infrastructure to CI infrastructure, I really mean, it's the transient nature of the information. Suppose I try a PR and then it fails and then I realize it was a bad idea and drop it. Then our badge will show that we're failing the build for how ever long it takes until some other action is taken on the library. The information is a summary, and has a good chance of being incorrect. We don't want to massage our PR status to make sure the badge shows something representative. A badge that simply linked and did not actually show status would be better. The Hypothesis project simply refuses all badges for that and related reasons, and I think they have a point.

I don't mind the crates badge, because it it's not summarizing in the same way, and is far less likely to mislead users.

**Comment by mulkieran** [comment]
We should probably remove the crates badge, since currently Fedora packaging considers it to contain an invalid URL. At warning level now, but it could change to an error anytime.

**Comment by jbaublitz** [comment]
> > I would hold off on this unless you generally think this information is not useful. Github actions may have a similar API to display that information.
> 
> I'm sure GitHub actions supplies something similar. But it's not that sort of transient, from CI infrastructure to CI infrastructure, I really mean, it's the transient nature of the information. Suppose I try a PR and then it fails and then I realize it was a bad idea and drop it. Then our badge will show that we're failing the build for how ever long it takes until some other action is taken on the library. The information is a summary, and has a good chance of being incorrect. We don't want to massage our PR status to make sure the badge shows something representative. A badge that simply linked and did not actually show status would be better. The Hypothesis project simply refuses all badges for that and related reasons, and I think they have a point.
> 
> I don't mind the crates badge, because it it's not summarizing in the same way, and is far less likely to mislead users.

The badge only shows the status of the master branch build, not the status of the latest PR.

**Comment by mulkieran** [comment]
> > > I would hold off on this unless you generally think this information is not useful. Github actions may have a similar API to display that information.
> > 
> > 
> > I'm sure GitHub actions supplies something similar. But it's not that sort of transient, from CI infrastructure to CI infrastructure, I really mean, it's the transient nature of the information. Suppose I try a PR and then it fails and then I realize it was a bad idea and drop it. Then our badge will show that we're failing the build for how ever long it takes until some other action is taken on the library. The information is a summary, and has a good chance of being incorrect. We don't want to massage our PR status to make sure the badge shows something representative. A badge that simply linked and did not actually show status would be better. The Hypothesis project simply refuses all badges for that and related reasons, and I think they have a point.
> > I don't mind the crates badge, because it it's not summarizing in the same way, and is far less likely to mislead users.
> 
> The badge only shows the status of the master branch build, not the status of the latest PR.

Right, it shows the status of the default branch. But the argument still holds, just not for an abandoned PR but for a failed build on the default branch. The reason I was thinking it was the PR was because it was showing cancelled builds until this morning. But Travis has been cancelling builds on this master branch as PRs get merged before the old build can get started and that's the explanation of the permanent cancelled status. But explanations of failed builds could be many, and not related to the health of the project.

**Comment by mulkieran** [comment]
We agreed in standup to go ahead and remove these badges.
