### ISSUE TITLE
Use bindgen to dynamically generate low-level ioctl bindings

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#623]
Currently, our file ```dm_ioctl.rs``` contains low-level bindings to the ioctl data structures that were generated at some prior time using bindgen as well as some additional code that was added later.

We would be better off using bindgen in the build process to dynamically generate the bindings and adding a more abstract layer separately as necessary.

**Comment by jbaublitz** [comment]
So far, I've bumped into this: https://github.com/rust-lang/rust-bindgen/issues/2041
