### ISSUE TITLE
Make DmError able to be cloned

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/devicemapper-rs#644]
Related to straits-storage/stratisd#2664

First, investigate whether this is possible with the error chaining crate. If it is, provide a `Clone` implementation given that in stratisd, we have a `DmError` that is part of a `lazy_static` expression so we cannot move it. It would be preferable to be able to clone it rather that stringifying it and wrapping it as a message.

**Comment by jbaublitz** [comment]
@mulkieran Please take a look at https://github.com/rust-lang-nursery/error-chain/issues/134. It appears that we cannot implement `Clone` for `DmError`. How would you like me to proceed?

**Comment by mulkieran** [comment]
@jbaublitz When you have a chance, look into seeing if we can just drop our dependency on ```error_chain``` in devicemapper entirely, as I believe that would solve the problem. But this obstacle should not block https://github.com/stratis-storage/stratisd/pull/2667.

**Comment by mulkieran** [comment]
So, dropping dependency on error_chain is not so hard, but ```std::io::Error``` is not cloneable. Also, I'ld like to drop ```fn description``` implementation for outer error, see #657. So, might as well defer until after next release.
