### ISSUE TITLE
Consider adding logging infrastructure to devicemapper-rs

### ISSUE THREAD

**Issue by bmr-cymru** [stratis-storage/devicemapper-rs#768]
There are situations where it would be useful to have more insight into the low-level operations being carried out in devicemapper-rs. This is especially the case with the work to implement [udev cookie semaphore support](https://github.com/bmr-cymru/devicemapper-rs/commits/bmr-udev-sync-v2) where it is often necessary to correlate events in the test (and the cookie values they generate) with the system udev logs.

While it's possible to get so far with `println!()` it would be very helpful to at least have the option of enabling straightforward, timestamped logs for the critical interactions with other subsystems.

This should follow the log pattern for a library crate permitting users of the crate to configure whatever concrete logger is needed.

**Comment by mulkieran** [comment]
This can be considered to be in progress, in connection with #774
