### ISSUE TITLE
Should we make gen_default_table methods public?

### ISSUE THREAD

**Issue by jbaublitz** [stratis-storage/devicemapper-rs#840]
Related to #839 and https://github.com/stratis-storage/stratisd/pull/3274

It's unclear to me whether they're of much use to people outside of this group. If they are, I'd say we should. If they aren't, I'm happy to reimplement the logic where I need to.

**Comment by mulkieran** [comment]
I don't think we should. I think they were a hack to begin with, and very stratisd specific. What should have happened is that it should have been possible to pass the TargetParams or maybe better the whole TargetTable to the new() methods, and clients of the library could pass whatever was useful to them. We even have an issue about this[1], but we have never had the time to address it.

[1] https://github.com/stratis-storage/devicemapper-rs/issues/400
