### ISSUE TITLE
Why does DM::table_deps() require a Device to identify the device

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#86]
The other methods take a ```&DevId```.

**Comment by agrover** [comment]
looking at the commit log, it looks like it was originally implemented this way. It should be ok to make it take a &DevId.

**Comment by mulkieran** [comment]
Probably becomes it makes implementing ```depends_on()``` easier.

**Comment by mulkieran** [comment]
SEe #103.

**Comment by mulkieran** [comment]
Related: #106.

**Comment by mulkieran** [comment]
Resolved by #137...it now takes a DevId like the other methods.
