### ISSUE TITLE
We know that the ioctl call for device_rename does not update the appropriate field to the new name

### ISSUE THREAD

**Issue by mulkieran** [stratis-storage/devicemapper-rs#90]
We don't know whether this is a bug or a feature or how to find out. We don't know whether the same occurs for UUIDs, but that is easy to find out. We might look at dmlib for some hints.

**Comment by agrover** [comment]
see also #92

**Comment by agrover** [comment]
dm-ioctl.h annotates other fields in struct dm_ioctl as "in/out", "out", but name is not annotated. Should we assume this means it is "in"? This would suggest it is not a bug but expected behavior that it was not updated upon rename.

**Comment by agrover** [comment]
fwiw nothing is annotated as "in".
